name: client
description: Test flutter http connectivity.

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true