import { readFile } from 'node:fs/promises'

import { runBdkTestSuite } from './test-suite.mjs'

const moduleName = process.argv[2] ?? 'bdk-core.mjs'
const isBrowserBuild = moduleName.includes('.browser.')
const moduleUrl = new URL(moduleName, import.meta.url)
const wasmUrl = new URL(moduleName.replace(/\.mjs$/, '.wasm'), import.meta.url)

// Exercise the browser-only loader in Node without reintroducing Node support
// into that loader. Providing wasmBinary bypasses fetch; `window` selects the
// web branch generated by Emscripten.
if (isBrowserBuild) globalThis.window = globalThis
const { default: createBdkModule } = await import(moduleUrl.href)
const moduleOptions = isBrowserBuild ? { wasmBinary: await readFile(wasmUrl) } : {}
const bdk = await createBdkModule(moduleOptions)

await runBdkTestSuite({ bdk, createBdkModule, moduleOptions, label: moduleName })
