import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const moduleName = process.argv[2] ?? 'bdk-core.mjs'
const isBrowserBuild = moduleName.includes('.browser.')
const moduleUrl = new URL(moduleName, import.meta.url)
const wasmUrl = new URL(moduleName.replace(/\.mjs$/, '.wasm'), import.meta.url)

// Exercise the browser-only loader in Node without reintroducing Node support
// into that loader. Providing wasmBinary bypasses fetch; `window` selects the
// web branch generated by Emscripten.
if (isBrowserBuild) globalThis.window = globalThis
const { default: createBdkModule } = await import(moduleUrl.href)
const moduleOptions = isBrowserBuild ? { wasmBinary: await readFile(wasmUrl) } : {}

const vectors = JSON.parse(
  await readFile(new URL('./vectors.json', import.meta.url), 'utf8')
)

function fromHex (hex) {
  if (hex.length % 2 !== 0) throw new Error('hex must have an even length')
  const bytes = new Uint8Array(hex.length / 2)
  for (let index = 0; index < bytes.length; index++) {
    bytes[index] = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16)
  }
  return bytes
}

function toVector (Type, values) {
  const vector = new Type()
  for (const value of values) vector.push_back(value)
  return vector
}

function concatenate (arrays, Type = Uint8Array) {
  const offsets = new Uint32Array(arrays.length + 1)
  let length = 0
  for (let index = 0; index < arrays.length; index++) {
    length += arrays[index].length
    offsets[index + 1] = length
  }
  const result = new Type(length)
  let position = 0
  for (const array of arrays) {
    result.set(array, position)
    position += array.length
  }
  return { values: result, offsets }
}

function readVarInt (bytes, start) {
  const prefix = bytes[start]
  if (prefix < 0xfd) return { value: prefix, end: start + 1 }
  if (prefix === 0xfd) return { value: bytes[start + 1] | (bytes[start + 2] << 8), end: start + 3 }
  throw new Error('test vector varint exceeds the supported fixture size')
}

function readUInt64LE (bytes, start) {
  let value = 0
  for (let index = 7; index >= 0; index--) value = value * 256 + bytes[start + index]
  return value
}

function rawTransactionAndSpendsFromEF (ef) {
  const rawParts = [ef.slice(0, 4)]
  let position = 10
  const inputCount = readVarInt(ef, position)
  rawParts.push(ef.slice(position, inputCount.end))
  position = inputCount.end
  const spends = []
  for (let index = 0; index < inputCount.value; index++) {
    const inputStart = position
    position += 36
    const unlockingLength = readVarInt(ef, position)
    position = unlockingLength.end + unlockingLength.value + 4
    rawParts.push(ef.slice(inputStart, position))
    const sourceSatoshis = readUInt64LE(ef, position)
    position += 8
    const lockingLength = readVarInt(ef, position)
    position = lockingLength.end
    const lockingScript = ef.slice(position, position + lockingLength.value)
    position += lockingLength.value
    spends.push({ inputIndex: index, sourceSatoshis, lockingScript })
  }
  rawParts.push(ef.slice(position))
  return { transaction: concatenate(rawParts).values, spends }
}

const bdk = await createBdkModule(moduleOptions)
const results = []

for (const vector of vectors) {
  const ef = fromHex(vector.extendedTx)
  const extendedTx = toVector(bdk.VectorUInt8, ef)
  const utxoHeights = toVector(bdk.VectorInt32, vector.utxoHeights)
  const customFlags = new bdk.VectorUInt32()
  try {
    const legacy = bdk.VerifyScript(
      extendedTx,
      utxoHeights,
      vector.blockHeight,
      vector.consensus,
      customFlags
    )
    const bulk = bdk.VerifyScriptArray(
      ef,
      Int32Array.from(vector.utxoHeights),
      vector.blockHeight,
      vector.consensus,
      new Uint32Array()
    )
    const network = bdk.VerifyScriptArrayNetwork(
      ef,
      Int32Array.from(vector.utxoHeights),
      vector.blockHeight,
      vector.consensus,
      new Uint32Array(),
      0
    )
    assert.deepEqual(legacy, vector.expected, `${vector.name} legacy ABI`)
    assert.deepEqual(bulk, vector.expected, `${vector.name} bulk ABI`)
    assert.deepEqual(network, vector.expected, `${vector.name} network ABI`)

    const { transaction, spends } = rawTransactionAndSpendsFromEF(ef)
    const spend = bdk.VerifySpendArray(
      transaction,
      spends[0].inputIndex,
      spends[0].lockingScript,
      spends[0].sourceSatoshis,
      vector.utxoHeights[0],
      vector.blockHeight,
      vector.consensus,
      false,
      0,
      0
    )
    assert.deepEqual(spend, vector.expected, `${vector.name} Spend ABI`)
    results.push({ vector, ef, transaction, spend: spends[0] })
    console.log(`ok - ${vector.name}: domain=${bulk.domain} code=${bulk.code}`)
  } finally {
    extendedTx.delete()
    utxoHeights.delete()
    customFlags.delete()
  }
}

const packedTransactions = concatenate(results.map(result => result.ef))
const packedHeights = concatenate(
  results.map(result => Int32Array.from(result.vector.utxoHeights)),
  Int32Array
)
const emptyFlagOffsets = new Uint32Array(results.length + 1)
const batch = bdk.VerifyScriptBatchArray(
  packedTransactions.values,
  packedTransactions.offsets,
  packedHeights.values,
  packedHeights.offsets,
  Int32Array.from(results.map(result => result.vector.blockHeight)),
  Uint8Array.from(results.map(result => result.vector.consensus ? 1 : 0)),
  new Uint32Array(),
  emptyFlagOffsets,
  0
)
assert.deepEqual(
  Array.from(batch),
  results.flatMap(result => [result.vector.expected.domain, result.vector.expected.code]),
  'transaction batch ABI'
)

const packedRawTransactions = concatenate(results.map(result => result.transaction))
const packedLockingScripts = concatenate(results.map(result => result.spend.lockingScript))
const spendBatch = bdk.VerifySpendBatchArray(
  packedRawTransactions.values,
  packedRawTransactions.offsets,
  Uint32Array.from(results.map(result => result.spend.inputIndex)),
  packedLockingScripts.values,
  packedLockingScripts.offsets,
  Float64Array.from(results.map(result => result.spend.sourceSatoshis)),
  Int32Array.from(results.map(result => result.vector.utxoHeights[0])),
  Int32Array.from(results.map(result => result.vector.blockHeight)),
  Uint8Array.from(results.map(result => result.vector.consensus ? 1 : 0)),
  new Uint8Array(results.length),
  new Uint32Array(results.length),
  0
)
assert.deepEqual(
  Array.from(spendBatch),
  results.flatMap(result => [result.vector.expected.domain, result.vector.expected.code]),
  'Spend batch ABI'
)

const positive = results.find(result => result.vector.expected.domain === 0)
assert.ok(positive, 'positive fixture is present')
for (const [networkName, networkId] of [['TeraTestNet', 4], ['Tera Scaling Test Network', 5]]) {
  const networkResult = bdk.VerifyScriptArrayNetwork(
    positive.ef,
    Int32Array.from(positive.vector.utxoHeights),
    positive.vector.blockHeight,
    positive.vector.consensus,
    new Uint32Array(),
    networkId
  )
  assert.deepEqual(networkResult, positive.vector.expected, `${networkName} network ABI`)
}
assert.throws(
  () => bdk.VerifyScriptArrayNetwork(
    positive.ef,
    Int32Array.from(positive.vector.utxoHeights),
    positive.vector.blockHeight,
    positive.vector.consensus,
    new Uint32Array(),
    99
  ),
  undefined,
  'unknown network IDs fail closed'
)
assert.throws(
  () => bdk.VerifyScriptBatchArray(
    positive.ef,
    Uint32Array.from([0]),
    Int32Array.from(positive.vector.utxoHeights),
    Uint32Array.from([0]),
    new Int32Array(),
    new Uint8Array(),
    new Uint32Array(),
    Uint32Array.from([0]),
    0
  ),
  undefined,
  'malformed empty-batch offsets fail closed'
)
assert.throws(
  () => bdk.VerifySpendArray(
    positive.transaction,
    positive.spend.inputIndex,
    positive.spend.lockingScript,
    Number.MAX_SAFE_INTEGER + 1,
    positive.vector.utxoHeights[0],
    positive.vector.blockHeight,
    positive.vector.consensus,
    false,
    0,
    0
  ),
  undefined,
  'unsafe source amounts fail closed'
)
