add_executable(bdk_verify_benchmark verify_script_benchmark.cpp)
target_link_libraries(bdk_verify_benchmark PRIVATE bdk_core)
target_compile_features(bdk_verify_benchmark PRIVATE cxx_std_20)
target_compile_options(bdk_verify_benchmark PRIVATE -O3)
if(APPLE)
  target_link_options(bdk_verify_benchmark PRIVATE "LINKER:-dead_strip")
elseif(UNIX)
  target_link_options(bdk_verify_benchmark PRIVATE "LINKER:--gc-sections")
endif()
