name: Manual Build Dependencies

on:
  workflow_dispatch:

jobs:
  build-upload-dependencies:
    strategy:
      matrix:
        include:
          - os: linux-arm64-8-core
          - os: ubuntu-24.04
          - os: macos-15
          - os: macos-15
            arch: x86_64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      BOOST_VERSION : 1.85.0
      OPENSSL_VERSION : 3.4.0

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set Environment Variables
      run: |
        OS_ARCH="$(uname -s | tr 'A-Z' 'a-z')_$(uname -m)"
        if [[ "${{ matrix.os }}" == "macos-15" && "${{ matrix.arch }}" == "x86_64" ]]; then
          ## Force the OS_ARCH name for macos-15 to be x86_64 (by default it is amd)
          OS_ARCH="darwin_x86_64"
        fi
        PACKAGE_NAME="dependancies_$OS_ARCH"
        echo "Building $PACKAGE_NAME on $OS_ARCH"
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "BOOST_URL=https://github.com/boostorg/boost/releases/download/boost-$BOOST_VERSION/boost-$BOOST_VERSION-cmake.tar.gz" >> $GITHUB_ENV
        echo "OPENSSL_URL=https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" >> $GITHUB_ENV
        echo "INSTALL_DIR=${{ github.workspace }}/$PACKAGE_NAME" >> $GITHUB_ENV
        echo "BOOST_ROOT=${{ github.workspace }}/$PACKAGE_NAME/boost_$BOOST_VERSION" >> $GITHUB_ENV
        echo "OPENSSL_ROOT_DIR=${{ github.workspace }}/$PACKAGE_NAME/openssl_$OPENSSL_VERSION" >> $GITHUB_ENV
        cat $GITHUB_ENV

    - name: Prepare Environment
      run: |
        if [[ ${{ matrix.os }} == *'ubuntu'* ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential g++ wget
        fi
        mkdir -p $BOOST_ROOT
        mkdir -p $OPENSSL_ROOT_DIR

    - name: Build Boost using cmake
      run: |
        wget -q $BOOST_URL -O "boost-$BOOST_VERSION-cmake.tar.gz"
        tar -xzf "boost-$BOOST_VERSION-cmake.tar.gz"
        mkdir -p "boost-$BOOST_VERSION/build"
        if [[ "${{ matrix.os }}" == "macos-15" && "${{ matrix.arch }}" == "x86_64" ]]; then
          echo "Force to build boost with arch x86_64 for macos-15 (which is an arm machine) ..."

          ## Build x86_64 on macos-15 requires to skip the Boost:context. There are 2 ways
          ##   - exclude context and all related dependencies
          ##   - include only boost modules that are required by bsv (search for AX_BOOST_* in bsv source)
          #cmake -B "./boost-$BOOST_VERSION/build" -S "./boost-$BOOST_VERSION" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="$BOOST_ROOT" -DBOOST_EXCLUDE_LIBRARIES="context;coroutine;coroutine2;fiber;fiber_numa;asio;cobalt;log;log_setup" 
          cmake -B "./boost-$BOOST_VERSION/build" -S "./boost-$BOOST_VERSION" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="$BOOST_ROOT" -DBOOST_INCLUDE_LIBRARIES="system;filesystem;program_options;thread;chrono;test"
        else
          cmake -B "./boost-$BOOST_VERSION/build" -S "./boost-$BOOST_VERSION" -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="$BOOST_ROOT" -DBOOST_INCLUDE_LIBRARIES="system;filesystem;program_options;thread;chrono;test"
        fi
        cmake --build "./boost-$BOOST_VERSION/build" -j$(nproc) --target install

    - name: Build OpenSSL
      run: |
        wget -q "$OPENSSL_URL" -O "openssl-$OPENSSL_VERSION.tar.gz"
        tar -xzf "openssl-$OPENSSL_VERSION.tar.gz"
        cd "openssl-$OPENSSL_VERSION"

        if [[ "${{ matrix.os }}" == "macos-15" && "${{ matrix.arch }}" == "x86_64" ]]; then
          echo "Force to build boost with arch x86_64 for macos-15 (which is an arm machine) ..."
          export KERNEL_BITS=64
          export CFLAGS="-arch x86_64"
          export LDFLAGS="-arch x86_64"
          ./config darwin64-x86_64-cc no-shared no-tests no-docs no-dso no-engine --prefix="$OPENSSL_ROOT_DIR" --openssldir="$OPENSSL_ROOT_DIR"
        else
          ./config no-shared no-tests no-docs no-dso no-engine --prefix="$OPENSSL_ROOT_DIR" --openssldir="$OPENSSL_ROOT_DIR"
        fi
        make -j$(nproc)
        make install_sw

    - name: Create archive
      run: |
        cd ${{ github.workspace }}
        tar -czf "$PACKAGE_NAME.tar.gz" "$PACKAGE_NAME"
      shell: bash

    - name: Upload artifact using github cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="depcy"
        ASSET_PATH="./${{ env.PACKAGE_NAME }}.tar.gz"
        gh release upload $TAG_NAME $ASSET_PATH --repo ${{ github.repository }} --clobber