name: Test workflow

on:
  workflow_dispatch:

jobs:
  build-bdk:
    strategy:
      matrix:
        os: [ubuntu-22.04-arm, macos-15-intel]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get OS ARCH Name
        run: |
          echo "OS_ARCH=$(uname -s | tr 'A-Z' 'a-z')_$(uname -m)" >> $GITHUB_ENV

      - name: Display G++ Version
        run: |
          echo "Checking G++ version..."
          g++ --version

      - name: Print OS and Architecture
        run: |
          echo "Running on OS: $(uname -s)"
          echo "CPU Architecture: $(uname -m)"
          echo "OS_ARCH: $OS_ARCH"