name: Test workflow

on:
  workflow_dispatch:

jobs:
  build-bdk:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
          - os: ubuntu-22.04
          - os: macos-15
          - os: macos-15-intel
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24.9
        if: matrix.os != 'ubuntu-22.04'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'
          check-latest: false

      - name: Get OS ARCH Name
        run: |
          echo "OS_ARCH=$(uname -s | tr 'A-Z' 'a-z')_$(uname -m)" >> $GITHUB_ENV

      - name: Display G++ Version
        run: |
          echo "Checking default g++ version..."
          g++ --version
          which g++

      - name: Display go version
        run: |
          echo "Checking default go version..."
          go version
          go env
          which go

      - name: Display cmake version
        run: |
          echo "Checking default cmake version..."
          cmake --version
          which cmake

      - name: Display OS ARCH
        run: |
          echo "echo OS_ARCH : $OS_ARCH"