name: Test workflow

on:
  workflow_dispatch:

jobs:
  build-bdk:
    strategy:
      matrix:
        os: [linux-arm64-8-core, ubuntu-22.04, macos-15]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get OS ARCH Name
        run: |
          echo "OS_ARCH=$(uname -s | tr 'A-Z' 'a-z')_$(uname -m)" >> $GITHUB_ENV

      - name: Display G++ Version
        run: |
          echo "Checking G++ version..."
          g++ --version

      - name: Check Runtime Libraries
        run: |
          echo "Compiling a simple test program..."
          echo '#include <iostream>' > test.cpp
          echo 'int main() { std::cout << "Hello, world!" << std::endl; return 0; }' >> test.cpp
          g++ test.cpp -o testcpp
          
          echo "Checking linked runtime libraries with ldd..."
          ldd testcpp

      - name: Check libstdc++ Version
        run: |
          echo "Checking libstdc++ version..."
          strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX || echo "libstdc++ not found"

      - name: Check glibc Version
        run: |
          echo "Checking glibc version..."
          ldd --version