name: Test workflow

on:
  workflow_dispatch:

jobs:
  build-bdk:
    strategy:
      matrix:
        include:
          - os: windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NASM
        shell: pwsh
        run: |
          choco install nasm --no-progress -y
          choco info nasm
          Write-Host "NASM installed."

      - name: Download OpenSSL 3.4.0 source
        shell: pwsh
        run: |
          $version = "3.4.0"
          $archive = "openssl-$version.tar.gz"
          $url = "https://www.openssl.org/source/openssl-$version.tar.gz"
          Write-Host "Downloading OpenSSL from $url ..."
          $ProgressPreference = 'SilentlyContinue'
          try {
            Start-BitsTransfer -Source $url -Destination $archive -ErrorAction Stop
          } catch {
            Write-Host "Start-BitsTransfer failed, falling back to curl..."
            curl.exe -L $url -o $archive
          }
          tar -xzf $archive
          Rename-Item "openssl-$version" "openssl"

      - name: Configure, Build and Install OpenSSL (MSVC x64)
        shell: cmd
        run: |
          REM Add NASM to PATH
          set PATH="C:\Program Files\NASM;%PATH%"

          "C:\Program Files\NASM\nasm.exe" -v
          
          REM Initialize Visual Studio environment
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          
          cd openssl
          perl Configure VC-WIN64A no-shared no-tests no-docs no-dso no-engine --prefix=%CD%\..\openssl-install
          nmake
          nmake install_sw

      - name: Verify Installation
        shell: pwsh
        run: |
          Write-Host "Installed headers:"
          Get-ChildItem "${{ github.workspace }}\openssl-install\include" -Recurse | Select-Object -First 10
          Write-Host "Installed libraries:"
          Get-ChildItem "${{ github.workspace }}\openssl-install\lib" -Recurse | Select-Object -First 10